default: &default
  api_url: <%= ENV["MESSAGE_API_URL"] %>
  msg_api_version: 1

development:
  <<: *default
  api_url: <%= ENV["MESSAGE_API_URL"] %>

docker:
  <<: *default

test:
  <<: *default
  api_url: <%= ENV["MESSAGE_API_URL"] %>

build_admin:
  <<: *default

build:
  <<: *default

demo_admin:
  <<: *default

demo:
  <<: *default

stage_admin:
  <<: *default

stage:
  <<: *default

training_admin:
  <<: *default

training:
  <<: *default

production_admin:
  <<: *default

production:
  <<: *default
