class LoadWosbAndEdwosbNaicsCodes < ActiveRecord::Migration
  def change
    wosb   = CertificateType.create!(name: 'wosb', title: 'Women-Owned Small Business')
    edwosb = CertificateType.create!(name: 'edwosb', title: 'Economically Disadvantaged Women-Owned Small Business')
    
    EligibleNaicCode.create certificate_type: wosb, naic_code: "115310", naic_code_description: "Support Activities for Forestry"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "221310", naic_code_description: "Water Supply and Irrigation Systems"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "221320", naic_code_description: "Sewage Treatment Facilities"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "221330", naic_code_description: "Steam and Air-Conditioning Supply"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "236115", naic_code_description: "New Single-Family Housing Construction (except For-Sale Builders)"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "236116", naic_code_description: "New Multifamily Housing Construction (except For-Sale Builders)"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "236117", naic_code_description: "New Housing For-Sale Builders"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "236118", naic_code_description: "Residential Remodelers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "236210", naic_code_description: "Industrial Building Construction"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "236220", naic_code_description: "Commercial and Institutional Building Construction"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "237110", naic_code_description: "Water and Sewer Line and Related Structures Construction"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "237120", naic_code_description: "Oil and Gas Pipeline and Related Structures Construction"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "237130", naic_code_description: "Power and Communication Line and Related Structures Construction"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "237310", naic_code_description: "Highway, Street, and Bridge Construction"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "237990", naic_code_description: "Other Heavy and Civil Engineering Construction"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238110", naic_code_description: "Poured Concrete Foundation and Structure Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238120", naic_code_description: "Structural Steel and Precast Concrete Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238130", naic_code_description: "Framing Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238140", naic_code_description: "Masonry Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238150", naic_code_description: "Glass and Glazing Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238160", naic_code_description: "Roofing Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238170", naic_code_description: "Siding Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238190", naic_code_description: "Other Foundation, Structure, and Building Exterior Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238210", naic_code_description: "Electrical Contractors and Other Wiring Installation Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238220", naic_code_description: "Plumbing, Heating, and Air-Conditioning Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238290", naic_code_description: "Other Building Equipment Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238310", naic_code_description: "Drywall and Insulation Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238320", naic_code_description: "Painting and Wall Covering Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238330", naic_code_description: "Flooring Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238340", naic_code_description: "Tile and Terrazzo Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238350", naic_code_description: "Finish Carpentry Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238390", naic_code_description: "Other Building Finishing Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238910", naic_code_description: "Site Preparation Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "238990", naic_code_description: "All Other Specialty Trade Contractors"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "311411", naic_code_description: "Frozen Fruit, Juice, and Vegetable Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "311412", naic_code_description: "Frozen Specialty Food Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "311421", naic_code_description: "Fruit and Vegetable Canning"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "311422", naic_code_description: "Specialty Canning"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "311423", naic_code_description: "Dried and Dehydrated Food Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "311811", naic_code_description: "Retail Bakeries"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "311812", naic_code_description: "Commercial Bakeries"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "311813", naic_code_description: "Frozen Cakes, Pies, and Other Pastries Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "311821", naic_code_description: "Cookie and Cracker Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "311824", naic_code_description: "Dry Pasta, Dough, and Flour Mixes Manufacturing from Purchased Flour"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "311830", naic_code_description: "Tortilla Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "314110", naic_code_description: "Carpet and Rug Mills"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "314120", naic_code_description: "Curtain and Linen Mills"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "314910", naic_code_description: "Textile Bag and Canvas Mills"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "314994", naic_code_description: "Rope, Cordage, Twine, Tire Cord, and Tire Fabric Mills"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "314999", naic_code_description: "All Other Miscellaneous Textile Product Mills"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "323111", naic_code_description: "Commercial Printing (except Screen and Books)"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "323113", naic_code_description: "Commercial Screen Printing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "323117", naic_code_description: "Books Printing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "323120", naic_code_description: "Support Activities for Printing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "324110", naic_code_description: "Petroleum Refineries"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "324121", naic_code_description: "Asphalt Paving Mixture and Block Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "324122", naic_code_description: "Asphalt Shingle and Coating Materials Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "324191", naic_code_description: "Petroleum Lubricating Oil and Grease Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "324199", naic_code_description: "All Other Petroleum and Coal Products Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332311", naic_code_description: "Prefabricated Metal Building and Component Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332312", naic_code_description: "Fabricated Structural Metal Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332313", naic_code_description: "Plate Work Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332321", naic_code_description: "Metal Window and Door Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332322", naic_code_description: "Sheet Metal Work Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332323", naic_code_description: "Ornamental and Architectural Metal Work Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332410", naic_code_description: "Power Boiler and Heat Exchanger Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332420", naic_code_description: "Metal Tank (Heavy Gauge) Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332431", naic_code_description: "Metal Can Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332439", naic_code_description: "Other Metal Container Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332510", naic_code_description: "Hardware Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332811", naic_code_description: "Metal Heat Treating"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332812", naic_code_description: "Metal Coating, Engraving (except Jewelry and Silverware), and Allied Services to Manufacturers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332813", naic_code_description: " Electroplating, Plating, Polishing, Anodizing, and Coloring"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332911", naic_code_description: "Industrial Valve Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332912", naic_code_description: "Fluid Power Valve and Hose Fitting Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332913", naic_code_description: "Plumbing Fixture Fitting and Trim Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332919", naic_code_description: "Other Metal Valve and Pipe Fitting Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332991", naic_code_description: "Ball and Roller Bearing Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332992", naic_code_description: "Small Arms Ammunition Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332993", naic_code_description: "Ammunition (except Small Arms) Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332994", naic_code_description: "Small Arms, Ordnance, and Ordnance Accessories Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332996", naic_code_description: "Fabricated Pipe and Pipe Fitting Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "332999", naic_code_description: "All Other Miscellaneous Fabricated Metal Product Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333111", naic_code_description: "Farm Machinery and Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333112", naic_code_description: "Lawn and Garden Tractor and Home Lawn and Garden Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333120", naic_code_description: "Construction Machinery Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333131", naic_code_description: "Mining Machinery and Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333132", naic_code_description: "Oil and Gas Field Machinery and Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333413", naic_code_description: "Industrial and Commercial Fan and Blower and Air Purification Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333414", naic_code_description: "Heating Equipment (except Warm Air Furnaces) Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333415", naic_code_description: "Air-Conditioning and Warm Air Heating Equipment and Commercial and Industrial Refrigeration Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333511", naic_code_description: "Industrial Mold Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333514", naic_code_description: "Special Die and Tool, Die Set, Jig, and Fixture Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333515", naic_code_description: "Cutting Tool and Machine Tool Accessory Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333517", naic_code_description: "Machine Tool Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333519", naic_code_description: "Rolling Mill and Other Metalworking Machinery Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333911", naic_code_description: "Pump and Pumping Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333912", naic_code_description: "Air and Gas Compressor Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333913", naic_code_description: "Measuring and Dispensing Pump Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333921", naic_code_description: "Elevator and Moving Stairway Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333922", naic_code_description: "Conveyor and Conveying Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333923", naic_code_description: "Overhead Traveling Crane, Hoist, and Monorail System Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333924", naic_code_description: "Industrial Truck, Tractor, Trailer, and Stacker Machinery Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333991", naic_code_description: "Power-Driven Handtool Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333992", naic_code_description: "Welding and Soldering Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333993", naic_code_description: "Packaging Machinery Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333994", naic_code_description: "Industrial Process Furnace and Oven Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333995", naic_code_description: "Fluid Power Cylinder and Actuator Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333996", naic_code_description: "Fluid Power Pump and Motor Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333997", naic_code_description: "Scale and Balance Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "333999", naic_code_description: "All Other Miscellaneous General Purpose Machinery Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "334510", naic_code_description: "Electromedical and Electrotherapeutic Apparatus Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "334511", naic_code_description: "Search, Detection, Navigation, Guidance, Aeronautical, and Nautical System and Instrument Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "334512", naic_code_description: "Automatic Environmental Control Manufacturing for Residential, Commercial, and Appliance Use"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "334513", naic_code_description: "Instruments and Related Products Manufacturing for Measuring, Displaying, and Controlling Industrial Process Variables"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "334514", naic_code_description: "Totalizing Fluid Meter and Counting Device Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "334515", naic_code_description: "Instrument Manufacturing for Measuring and Testing Electricity and Electrical Signals"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "334516", naic_code_description: "Analytical Laboratory Instrument Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "334517", naic_code_description: "Irradiation Apparatus Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "334519", naic_code_description: "Other Measuring and Controlling Device Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "334613", naic_code_description: "Blank Magnetic and Optical Recording Media Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "334614", naic_code_description: "Software and Other Prerecorded Compact Disc, Tape, and Record Reproducing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "336310", naic_code_description: "Motor Vehicle Gasoline Engine and Engine Parts Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "336320", naic_code_description: "Motor Vehicle Electrical and Electronic Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "336330", naic_code_description: "Motor Vehicle Steering and Suspension Components (except Spring) Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "336340", naic_code_description: "Motor Vehicle Brake System Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "336350", naic_code_description: "Motor Vehicle Transmission and Power Train Parts Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "336360", naic_code_description: "Motor Vehicle Seating and Interior Trim Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "336370", naic_code_description: "Motor Vehicle Metal Stamping"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "336390", naic_code_description: "Other Motor Vehicle Parts Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "336991", naic_code_description: "Motorcycle, Bicycle, and Parts Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "336992", naic_code_description: "Military Armored Vehicle, Tank, and Tank Component Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "336999", naic_code_description: "All Other Transportation Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "337110", naic_code_description: "Wood Kitchen Cabinet and Countertop Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "337121", naic_code_description: "Upholstered Household Furniture Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "337122", naic_code_description: "Nonupholstered Wood Household Furniture Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "337124", naic_code_description: "Metal Household Furniture Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "337125", naic_code_description: "Household Furniture (except Wood and Metal) Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "337127", naic_code_description: "Institutional Furniture Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339112", naic_code_description: "Surgical and Medical Instrument Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339113", naic_code_description: "Surgical Appliance and Supplies Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339114", naic_code_description: "Dental Equipment and Supplies Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339115", naic_code_description: "Ophthalmic Goods Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339116", naic_code_description: "Dental Laboratories"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339910", naic_code_description: "Jewelry and Silverware Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339920", naic_code_description: "Sporting and Athletic Goods Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339930", naic_code_description: "Doll, Toy, and Game Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339940", naic_code_description: "Office Supplies (except Paper) Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339950", naic_code_description: "Sign Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339991", naic_code_description: "Gasket, Packing, and Sealing Device Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339992", naic_code_description: "Musical Instrument Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339993", naic_code_description: "Fastener, Button, Needle, and Pin Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339994", naic_code_description: "Broom, Brush, and Mop Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339995", naic_code_description: " Burial Casket Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "339999", naic_code_description: "All Other Miscellaneous Manufacturing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "483111", naic_code_description: "Deep Sea Freight Transportation"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "483112", naic_code_description: "Deep Sea Passenger Transportation"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "483113", naic_code_description: "Coastal and Great Lakes Freight Transportation"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "483114", naic_code_description: "Coastal and Great Lakes Passenger Transportation"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "484210", naic_code_description: "Used Household and Office Goods Moving"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "484220", naic_code_description: "Specialized Freight (except Used Goods) Trucking, Local"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "484230", naic_code_description: "Specialized Freight (except Used Goods) Trucking, Long-Distance"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "488410", naic_code_description: "Motor Vehicle Towing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "488490", naic_code_description: "Other Support Activities for Road Transportation"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "493110", naic_code_description: "General Warehousing and Storage"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "493120", naic_code_description: "Refrigerated Warehousing and Storage"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "493130", naic_code_description: "Farm Product Warehousing and Storage"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "493190", naic_code_description: "Other Warehousing and Storage"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "511110", naic_code_description: "Newspaper Publishers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "511120", naic_code_description: "Periodical Publishers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "511130", naic_code_description: "Book Publishers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "511140", naic_code_description: "Directory and Mailing List Publishers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "511191", naic_code_description: "Greeting Card Publishers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "511199", naic_code_description: "All Other Publishers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "511210", naic_code_description: "Software Publishers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "512110", naic_code_description: "Motion Picture and Video Production"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "512120", naic_code_description: "Motion Picture and Video Distribution"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "512131", naic_code_description: "Motion Picture Theaters (except Drive-Ins)"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "512132", naic_code_description: "Drive-In Motion Picture Theaters"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "512191", naic_code_description: "Teleproduction and Other Postproduction Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "512199", naic_code_description: "Other Motion Picture and Video Industries"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "512210", naic_code_description: "Record Production"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "512220", naic_code_description: "Integrated Record Production/Distribution"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "512230", naic_code_description: "Music Publishers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "512240", naic_code_description: "Sound Recording Studios"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "512290", naic_code_description: "Other Sound Recording Industries"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "515111", naic_code_description: "Radio Networks"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "515112", naic_code_description: "Radio Stations"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "515120", naic_code_description: "Television Broadcasting"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "517210", naic_code_description: "Wireless Telecommunications Carriers (except Satellite)"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "517410", naic_code_description: "Satellite Telecommunications"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "517911", naic_code_description: "Telecommunications Resellers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "517919", naic_code_description: "All Other Telecommunications"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "518210", naic_code_description: "Data Processing, Hosting, and Related Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "519110", naic_code_description: "News Syndicates"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "519120", naic_code_description: "Libraries and Archives"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "519130", naic_code_description: "Internet Publishing and Broadcasting and Web Search Portals"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "519190", naic_code_description: "All Other Information Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "524113", naic_code_description: "Direct Life Insurance Carriers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "524114", naic_code_description: "Direct Health and Medical Insurance Carriers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "524126", naic_code_description: "Direct Property and Casualty Insurance Carriers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "524127", naic_code_description: "Direct Title Insurance Carriers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "524128", naic_code_description: "Other Direct Insurance (except Life, Health, and Medical) Carriers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "524130", naic_code_description: "Reinsurance Carriers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "524210", naic_code_description: "Insurance Agencies and Brokerages"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "524291", naic_code_description: "Claims Adjusting"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "524292", naic_code_description: "Third Party Administration of Insurance and Pension Funds"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "524298", naic_code_description: "All Other Insurance Related Activities"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "532111", naic_code_description: "Passenger Car Rental"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "532112", naic_code_description: "Passenger Car Leasing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "532120", naic_code_description: "Truck, Utility Trailer, and RV (Recreational Vehicle) Rental and Leasing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "532411", naic_code_description: "Commercial Air, Rail, and Water Transportation Equipment Rental and Leasing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "532412", naic_code_description: "Construction, Mining, and Forestry Machinery and Equipment Rental and Leasing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "532420", naic_code_description: "Office Machinery and Equipment Rental and Leasing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "532490", naic_code_description: "Other Commercial and Industrial Machinery and Equipment Rental and Leasing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541110", naic_code_description: "Offices of Lawyers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541191", naic_code_description: "Title Abstract and Settlement Offices"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541199", naic_code_description: "All Other Legal Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541211", naic_code_description: "Offices of Certified Public Accountants"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541213", naic_code_description: "Tax Preparation Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541214", naic_code_description: "Payroll Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541219", naic_code_description: "Other Accounting Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541310", naic_code_description: "Architectural Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541320", naic_code_description: "Landscape Architectural Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541330", naic_code_description: "Engineering Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541340", naic_code_description: "Drafting Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541350", naic_code_description: "Building Inspection Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541360", naic_code_description: "Geophysical Surveying and Mapping Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541370", naic_code_description: "Surveying and Mapping (except Geophysical) Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541380", naic_code_description: "Testing Laboratories"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541511", naic_code_description: "Custom Computer Programming Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541512", naic_code_description: "Computer Systems Design Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541513", naic_code_description: "Computer Facilities Management Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541519", naic_code_description: "Other Computer Related Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541611", naic_code_description: "Administrative Management and General Management Consulting Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541612", naic_code_description: "Human Resources Consulting Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541613", naic_code_description: "Marketing Consulting Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541614", naic_code_description: "Process, Physical Distribution, and Logistics Consulting Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541618", naic_code_description: "Other Management Consulting Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541620", naic_code_description: "Environmental Consulting Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541690", naic_code_description: "Other Scientific and Technical Consulting Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541711", naic_code_description: "Research and Development in Biotechnology"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541712", naic_code_description: "Research and Development in the Physical, Engineering, and Life Sciences (except Biotechnology)"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541720", naic_code_description: "Research and Development in the Social Sciences and Humanities"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541810", naic_code_description: "Advertising Agencies"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541820", naic_code_description: "Public Relations Agencies"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541830", naic_code_description: "Media Buying Agencies"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541840", naic_code_description: "Media Representatives"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541850", naic_code_description: "Outdoor Advertising"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541860", naic_code_description: "Direct Mail Advertising"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541870", naic_code_description: "Advertising Material Distribution Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541890", naic_code_description: "Other Services Related to Advertising"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541910", naic_code_description: "Marketing Research and Public Opinion Polling"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541921", naic_code_description: "Photography Studios, Portrait"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541922", naic_code_description: "Commercial Photography"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541930", naic_code_description: "Translation and Interpretation Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541940", naic_code_description: "Veterinary Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "541990", naic_code_description: "All Other Professional, Scientific, and Technical Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561210", naic_code_description: "Facilities Support Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561510", naic_code_description: "Travel Agencies"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561520", naic_code_description: "Tour Operators"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561591", naic_code_description: "Convention and Visitors Bureaus"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561599", naic_code_description: "All Other Travel Arrangement and Reservation Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561611", naic_code_description: "Investigation Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561612", naic_code_description: "Security Guards and Patrol Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561613", naic_code_description: "Armored Car Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561621", naic_code_description: "Security Systems Services (except Locksmiths)"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561622", naic_code_description: "Locksmiths"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561710", naic_code_description: "Exterminating and Pest Control Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561720", naic_code_description: "Janitorial Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561730", naic_code_description: "Landscaping Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561740", naic_code_description: "Carpet and Upholstery Cleaning Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561790", naic_code_description: "Other Services to Buildings and Dwellings"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561910", naic_code_description: "Packaging and Labeling Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561920", naic_code_description: "Convention and Trade Show Organizers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "561990", naic_code_description: "All Other Support Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "562211", naic_code_description: "Hazardous Waste Treatment and Disposal"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "562212", naic_code_description: "Solid Waste Landfill"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "562213", naic_code_description: "Solid Waste Combustors and Incinerators"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "562219", naic_code_description: "Other Nonhazardous Waste Treatment and Disposal"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "562910", naic_code_description: "Remediation Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "562920", naic_code_description: "Materials Recovery Facilities"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "562991", naic_code_description: "Septic Tank and Related Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "562998", naic_code_description: "All Other Miscellaneous Waste Management Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "611310", naic_code_description: "Colleges, Universities, and Professional Schools"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "611410", naic_code_description: "Business and Secretarial Schools"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "611420", naic_code_description: "Computer Training"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "611430", naic_code_description: "Professional and Management Development Training"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "611610", naic_code_description: "Fine Arts Schools"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "611620", naic_code_description: "Sports and Recreation Instruction"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "611630", naic_code_description: "Language Schools"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "611691", naic_code_description: "Exam Preparation and Tutoring"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "611692", naic_code_description: "Automobile Driving Schools"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "611699", naic_code_description: "All Other Miscellaneous Schools and Instruction"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "611710", naic_code_description: "Educational Support Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621111", naic_code_description: "Offices of Physicians (except Mental Health Specialists)"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621112", naic_code_description: "Offices of Physicians, Mental Health Specialists"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621410", naic_code_description: "Family Planning Centers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621420", naic_code_description: "Outpatient Mental Health and Substance Abuse Centers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621491", naic_code_description: "HMO Medical Centers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621492", naic_code_description: "Kidney Dialysis Centers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621493", naic_code_description: "Freestanding Ambulatory Surgical and Emergency Centers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621498", naic_code_description: "All Other Outpatient Care Centers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621511", naic_code_description: "Medical Laboratories"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621512", naic_code_description: "Diagnostic Imaging Centers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621910", naic_code_description: "Ambulance Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621991", naic_code_description: "Blood and Organ Banks"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "621999", naic_code_description: "All Other Miscellaneous Ambulatory Health Care Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "622110", naic_code_description: "General Medical and Surgical Hospitals"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "623110", naic_code_description: "Nursing Care Facilities (Skilled Nursing Facilities)"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "624210", naic_code_description: "Community Food Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "624221", naic_code_description: "Temporary Shelters"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "624229", naic_code_description: "Other Community Housing Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "624230", naic_code_description: "Emergency and Other Relief Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "711211", naic_code_description: "Sports Teams and Clubs"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "711212", naic_code_description: "Racetracks"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "711219", naic_code_description: "Other Spectator Sports"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "711310", naic_code_description: "Promoters of Performing Arts, Sports, and Similar Events with Facilities"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "711320", naic_code_description: "Promoters of Performing Arts, Sports, and Similar Events without Facilities"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "711410", naic_code_description: "Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "711510", naic_code_description: "Independent Artists, Writers, and Performers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "721110", naic_code_description: "Hotels (except Casino Hotels) and Motels"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "721120", naic_code_description: "Casino Hotels"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "721191", naic_code_description: "Bed-and-Breakfast Inns"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "721199", naic_code_description: "All Other Traveler Accommodation"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "721211", naic_code_description: "RV (Recreational Vehicle) Parks and Campgrounds"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "721214", naic_code_description: "Recreational and Vacation Camps (except Campgrounds)"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "722511", naic_code_description: "Full-Service Restaurants"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "722513", naic_code_description: "Limited-Service Restaurants"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "722514", naic_code_description: "Cafeterias, Grill Buffets, and Buffets"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "722515", naic_code_description: "Snack and Nonalcoholic Beverage Bars"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811111", naic_code_description: "General Automotive Repair"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811112", naic_code_description: "Automotive Exhaust System Repair"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811113", naic_code_description: "Automotive Transmission Repair"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811118", naic_code_description: "Other Automotive Mechanical and Electrical Repair and Maintenance"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811121", naic_code_description: "Automotive Body, Paint, and Interior Repair and Maintenance"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811122", naic_code_description: "Automotive Glass Replacement Shops"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811191", naic_code_description: "Automotive Oil Change and Lubrication Shops"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811192", naic_code_description: "Car Washes"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811198", naic_code_description: "All Other Automotive Repair and Maintenance"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811211", naic_code_description: "Consumer Electronics Repair and Maintenance"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811212", naic_code_description: "Computer and Office Machine Repair and Maintenance"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811213", naic_code_description: "Communication Equipment Repair and Maintenance"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811219", naic_code_description: "Other Electronic and Precision Equipment Repair and Maintenance"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "811310", naic_code_description: "Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812111", naic_code_description: "Barber Shops"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812112", naic_code_description: "Beauty Salons"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812113", naic_code_description: "Nail Salons"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812191", naic_code_description: "Diet and Weight Reducing Centers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812199", naic_code_description: "Other Personal Care Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812310", naic_code_description: "Coin-Operated Laundries and Drycleaners"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812320", naic_code_description: "Drycleaning and Laundry Services (except Coin-Operated)"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812331", naic_code_description: "Linen Supply"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812332", naic_code_description: "Industrial Launderers"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812910", naic_code_description: "Pet Care (except Veterinary) Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812921", naic_code_description: "Photofinishing Laboratories (except One-Hour)"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812922", naic_code_description: "One-Hour Photofinishing"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812930", naic_code_description: "Parking Lots and Garages"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "812990", naic_code_description: "All Other Personal Services"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "813110", naic_code_description: "Religious Organizations"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "813910", naic_code_description: "Business Associations"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "813920", naic_code_description: "Professional Organizations"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "813930", naic_code_description: "Labor Unions and Similar Labor Organizations"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "813940", naic_code_description: "Political Organizations"
    EligibleNaicCode.create certificate_type: wosb, naic_code: "813990", naic_code_description: "Other Similar Organizations (except Business, Professional, Labor, and Political Organizations)"
    
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "315210", naic_code_description: "Cut and Sew Apparel Contractors"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "315220", naic_code_description: "Men's and Boys' Cut and Sew Apparel Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "315240", naic_code_description: "Women's, Girls', and Infants' Cut and Sew Apparel Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "315280", naic_code_description: "Other Cut and Sew Apparel Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "321911", naic_code_description: "Wood Window and Door Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "321912", naic_code_description: "Cut Stock, Resawing Lumber, and Planing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "321918", naic_code_description: "Other Millwork (including Flooring)"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "321920", naic_code_description: "Wood Container and Pallet Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "321991", naic_code_description: "Manufactured Home (Mobile Home) Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "321992", naic_code_description: "Prefabricated Wood Building Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "321999", naic_code_description: "All Other Miscellaneous Wood Product Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "325910", naic_code_description: "Printing Ink Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "325920", naic_code_description: "Explosives Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "325991", naic_code_description: "Custom Compounding of Purchased Resins"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "325992", naic_code_description: "Photographic Film, Paper, Plate, and Chemical Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "325998", naic_code_description: "All Other Miscellaneous Chemical Product and Preparation Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "333314", naic_code_description: "Optical Instrument and Lens Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "333316", naic_code_description: "Photographic and Photocopying Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "333318", naic_code_description: "Other Commercial and Service Industry Machinery Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "334210", naic_code_description: "Telephone Apparatus Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "334220", naic_code_description: "Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "334290", naic_code_description: "Other Communications Equipment Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "335311", naic_code_description: "Power, Distribution, and Specialty Transformer Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "335312", naic_code_description: "Motor and Generator Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "335313", naic_code_description: "Switchgear and Switchboard Apparatus Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "335314", naic_code_description: "Relay and Industrial Control Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "335911", naic_code_description: "Storage Battery Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "335912", naic_code_description: "Primary Battery Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "335921", naic_code_description: "Fiber Optic Cable Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "335929", naic_code_description: "Other Communication and Energy Wire Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "335931", naic_code_description: "Current-Carrying Wiring Device Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "335932", naic_code_description: "Noncurrent-Carrying Wiring Device Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "335991", naic_code_description: "Carbon and Graphite Product Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "335999", naic_code_description: "All Other Miscellaneous Electrical Equipment and Component Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "337211", naic_code_description: "Wood Office Furniture Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "337212", naic_code_description: "Custom Architectural Woodwork and Millwork Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "337214", naic_code_description: "Office Furniture (except Wood) Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "337215", naic_code_description: "Showcase, Partition, Shelving, and Locker Manufacturing"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "484110", naic_code_description: "General Freight Trucking, Local"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "484121", naic_code_description: "General Freight Trucking, Long-Distance, Truckload"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "484122", naic_code_description: "General Freight Trucking, Long-Distance, Less Than Truckload"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "488510", naic_code_description: "Freight Transportation Arrangement"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "488991", naic_code_description: "Packing and Crating"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "488999", naic_code_description: "All Other Support Activities for Transportation"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "517110", naic_code_description: "Wired Telecommunications Carriers"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "531110", naic_code_description: "Lessors of Residential Buildings and Dwellings"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "531120", naic_code_description: "Lessors of Nonresidential Buildings (except Miniwarehouses)"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "531130", naic_code_description: "Lessors of Miniwarehouses and Self-Storage Units"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "531190", naic_code_description: "Lessors of Other Real Estate Property"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "541410", naic_code_description: "Interior Design Services"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "541420", naic_code_description: "Industrial Design Services"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "541430", naic_code_description: "Graphic Design Services"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "541490", naic_code_description: "Other Specialized Design Services"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "561110", naic_code_description: "Office Administrative Services"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "561410", naic_code_description: "Document Preparation Services"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "561421", naic_code_description: "Telephone Answering Services"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "561422", naic_code_description: "Telemarketing Bureaus and Other Contact Centers"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "561431", naic_code_description: "Private Mail Centers"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "561439", naic_code_description: "Other Business Service Centers (including Copy Shops)"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "561440", naic_code_description: "Collection Agencies"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "561450", naic_code_description: "Credit Bureaus"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "561491", naic_code_description: "Repossession Services"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "561492", naic_code_description: "Court Reporting and Stenotype Services"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "561499", naic_code_description: "All Other Business Support Services"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "562111", naic_code_description: "Solid Waste Collection"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "562112", naic_code_description: "Hazardous Waste Collection"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "562119", naic_code_description: "Other Waste Collection"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "611511", naic_code_description: "Cosmetology and Barber Schools"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "611512", naic_code_description: "Flight Training"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "611513", naic_code_description: "Apprenticeship Training"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "611519", naic_code_description: "Other Technical and Trade Schools"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "624310", naic_code_description: "Vocational Rehabilitation Services"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "722310", naic_code_description: "Food Service Contractors"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "722320", naic_code_description: "Caterers"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "722330", naic_code_description: "Mobile Food Services"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "811411", naic_code_description: "Home and Garden Equipment Repair and Maintenance"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "811412", naic_code_description: "Appliance Repair and Maintenance"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "811420", naic_code_description: "Reupholstery and Furniture Repair"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "811430", naic_code_description: "Footwear and Leather Goods Repair"
    EligibleNaicCode.create certificate_type: edwosb, naic_code: "811490", naic_code_description: "Other Personal and Household Goods Repair and Maintenance"
  end
end
