class CreateReviews < ActiveRecord::Migration
  def change

    # The reviews table is for tracking analyst reviews on sba applications and certifications
    create_table :reviews do |t|
      t.text :type                      # sub class of review "CertificateReview::InitialReview" since we'll have different types of reviews which may eventually have their own workflows
      t.text :case_number               # autogenerated unique identifier analysts can use to refer to a review, in the format of MZ12312341 (two letters followed by timestamp number)
      t.references :sba_application     # what application is the review associated with
      t.references :certificate         # what certificate is this review for?
      t.integer :current_assignment_id  # refers to the current owner / reviewer and surpervisor (analysts)
      t.text :workflow_state            # used by the workflow gem to track the current state of the review
      t.integer :determination_id       # references the resulting determination made on the review

      t.datetime :deleted_at            # for soft deletes
      t.timestamps null: false
    end

    add_index :reviews, [:sba_application_id, :deleted_at], name: :index_reviews_on_app_d
    add_index :reviews, [:certificate_id, :deleted_at], name: :index_reviews_on_cert_d
    add_index :reviews, [:current_assignment_id, :deleted_at], name: :index_reviews_on_ca_d

    add_foreign_key :reviews, :sba_applications
    add_foreign_key :reviews, :certificates
  end
end
